# Pills

#            󰫢

add_newline = true
palette = "default"

format = """
$status\
$directory\
$python\
$git_status\
$git_metrics\
$cmd_duration\
$time\
"""

###########################################

[palettes.default]
prompt_ok  = "#BED29A"
prompt_err = "#BA5641"
separator  = "#D9A362"
background = "#2D313D"
icon       = "#2D313D"

directory  = "#D9A362"
duration   = "#E26F31"
status     = "#D9A362"
git_branch = "#BED29A"
git_status = "#9CBA75"
env_color = "#E6C068"

###########################################

[fill]
symbol = ' '

[character]
success_symbol = "[❯](fg:prompt_ok)"
error_symbol = "[❯](fg:prompt_err)"

[status]
format = "[](fg:status)[ ](fg:icon bg:status)[](fg:status bg:background)[ $status](bg:background)[](fg:background)"
pipestatus = true
pipestatus_separator = ""
pipestatus_segment_format = "$status"
pipestatus_format = "[](fg:status)[ ](fg:icon bg:status)[](fg:status bg:background)[$pipestatus](bg:background)[](fg:background)"
disabled = false

[directory]
format = "[](fg:directory)[ ](fg:icon bg:directory)[](fg:directory bg:background)[ $path](bg:background)[](fg:background)"
truncate_to_repo = true
truncation_length = 0

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Repos" = "󰲋"

[git_branch]
format = "[](fg:git_branch)[](fg:icon bg:git_branch)[](fg:git_branch bg:background)[ $branch](bg:background)"

[git_status]
format = "[](fg:git_status)[$conflicted$stashed$modified$untracked](fg:icon bg:git_status)[](fg:git_status bg:background)"
modified = " "
untracked= " "
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'


[cmd_duration]
format = "[](fg:duration)[ ](fg:icon bg:duration)[](fg:duration bg:background)[ $duration](bg:background)[](fg:background)"
min_time = 500

[time]
format = "[](fg:duration)[⌚](fg:icon bg:duration)[](fg:duration bg:background)[ $time](bg:background)[](fg:background)"
disabled = true

[git_metrics]
added_style = "fg:git_status"
deleted_style = "fg:status"
format = "[](fg:git_status bg:background)[ +$added](fg:prompt_ok bg:background)[ -$deleted](fg:prompt_err bg:background)[](fg:background)"
disabled = false
only_nonzero_diffs = false

[python]
format = "[](fg:env_color bg:background)[$symbol](fg:icon bg:env_color)[](fg:env_color bg:background)[$version $virtualenv](fg:env_color bg:background)[](fg:background)"
symbol = ' '
pyenv_version_name = false
version_format = 'v$raw'